version: "3.8"

services:
  app:
    image: ghcr.io/hwisnu222/instac:main
    container_name: instac
    ports:
      - "8083:8000"
    restart: unless-stopped
    volumes:
      - ./instac/downloads:/app/server/downloads
    environment:
      - PYTHONUNBUFFERED=1
      - FASTAPI_ENV=production
